name: 'Action Auditor'
description: 'Detect exposed API Keys.'
inputs:
  github_token:
    description: "Get GitHub Token"
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - id: Print All Actions
      run: docker images
      shell: bash
